### ISSUE TITLE
Source code published with releases has the wrong `package.json` version

### ISSUE THREAD

**Issue by Aghassi** [devexperts/dxcharts-lite#160]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Describe the bug 😯

Your release process is not bumping the package.json before tar'ing up the source code put with each release on github. This means pulling 2.4.6 pulls 2.4.5 technically if you pull the github tgz.

### Link to minimal reproduction

Download the tar for the latest release

### Steps to Reproduce the Bug or Issue 🕹

Download the tar and untar it, Validate the package.json version in the resulting folder

### Expected behavior 🤔

package.json version should match the version on github

### Platform

Applies across the board

**Comment by disyakidneyshot** [comment]
Hello there @Aghassi! Yep, you're right, thanks for your report
We will work it out

**Comment by disyakidneyshot** [comment]
@Aghassi we changed release flow to escape this issue
Since @2.5.0 everything should be fine :)

P.S. here you can find main changes in release job https://github.com/devexperts/dxcharts-lite/commit/3a5c6f5016ebdb05f4dbd7d468cf0406cbfcaf03
