### ISSUE TITLE
Can you share the source code of the demo so that I can learn from it?

### ISSUE THREAD

**Issue by wuzxc1230123** [devexperts/dxcharts-lite#28]
### Duplicates

- [X] I have searched the proposed features

### Latest version

- [X] I have tested the latest version

### Suggestion ⭐

Can you share the source code of the demo so that I can learn from it?

**Comment by DeltaZN** [comment]
Hello!
So, basically, demo for lite consists of 4 cases:
<img width="1479" alt="image" src="https://github.com/devexperts/dxcharts-lite/assets/44753430/6e26409f-48d7-4891-9c90-1cd603f41ac3">

1. [chart type](https://github.com/devexperts/dxcharts-lite/blob/master/docs/how-to/chart-type/index.html)
2. [multiple series](https://github.com/devexperts/dxcharts-lite/blob/master/docs/how-to/set-and-update-candles/README.md)
3. [price scale](https://github.com/devexperts/dxcharts-lite/tree/master/docs/how-to/y-scale)
4. [custom colors](https://github.com/devexperts/dxcharts-lite/tree/master/docs/how-to/colors)
