### ISSUE TITLE
I would like to participate in the development of an open source project for C #, and how to participate in this project

### ISSUE THREAD

**Issue by wuzxc1230123** [devexperts/dxcharts-lite#29]
### Duplicates

- [X] I have searched the proposed features

### Latest version

- [X] I have tested the latest version

### Suggestion ⭐

I implement Blazor c # based on this Demo code. Can you teach me how to implement this function for a fee? I will open source these codes

### Motivation 🔦

I want to understand https://devexperts.com/dxcharts-demo/ Suggested implementation

### Examples 📃

I want to know https://devexperts.com/dxcharts-demo/ Those APIs were called

**Comment by DeltaZN** [comment]
answered [here](https://github.com/devexperts/dxcharts-lite/issues/28)
